name: ğŸš€ Test

on:
  check_suite:
    branches:
      - main

jobs:
  run:
    name: ğŸš€ Test
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš€ Test
        shell: bash
        run: |
          python3 -m unittest discover
